spring:
  application:
    name: financial-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/financial_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:4e339de6-3876-4ff6-a2af-8982ec2f82a1}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}