spring:
  application:
    name: financial-backend

  datasource:
    url: jdbc:mysql://localhost:3306/financial_db
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

#  # --- ---
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: ${UPLOAD_MAX_FILE_SIZE:10MB}
#      max-request-size: ${UPLOAD_MAX_REQUEST_SIZE:15MB}
#
#  # --- Đăng nhập Google OAuth2 (UC-01, FR-01) ---
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID:}
#            client-secret: ${GOOGLE_CLIENT_SECRET:}
#            scope:
#              - email
#              - profile
#
#  # --- Email ---
#  mail:
#    host: ${MAIL_HOST:smtp.gmail.com}
#    port: ${MAIL_PORT:587}
#    username: ${MAIL_USERNAME:}
#    password: ${MAIL_PASSWORD:}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
## -- JWT ---
#app:
#  jwt:
#    secret: ${JWT_SECRET:CHANGE_THIS_SECRET_KEY_TO_A_LONG_RANDOM_STRING}
#    expiration-ms: ${JWT_EXPIRATION_MS:86400000}      # 24 giờ
#    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}  # 7 ngày
#  cors:
#    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}
#
## --- Logging ---
#logging:
#  level:
#    root: INFO
#    com.personal.finance.backend: DEBUG
#    org.hibernate.SQL: DEBUG